version: 2.1

jobs:
  check-project:
    docker:
      - image: cimg/openjdk:17.0

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle.kts" }}
            - v1-dependencies-

      - run:
          name: Run Gradle Checks
          command: ./gradlew check --no-daemon --stacktrace

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle.kts" }}

      - store_test_results:
          path: build/test-results

workflows:
  build-and-test:
    jobs:
      - check-project
